### ISSUE TITLE
needs adaptation to 2.8?

### ISSUE THREAD

**Issue by j2l** [cheind/pytorch-blender#2]
On the develop branch, after changing path to call /blender2.8/blender.py in example.py and `python example.py --blend-path ~/Desktop/blender282/` I got an error:
```
Traceback (most recent call last):
  File "example.py", line 64, in <module>
    main()
  File "example.py", line 43, in main
    with bt.BlenderLauncher(num_instances=4, script='blender28/blender.py', scene='blender28/scene.blend', blend_path=args.blend_path) as bl:        
  File "/home/pm/Desktop/APPS/pytorch-blender/blendtorch/torch/launcher.py", line 52, in __init__
    self.blender_info = discover_blender(self.blend_path)
  File "/home/pm/Desktop/APPS/pytorch-blender/blendtorch/torch/finder.py", line 56, in discover_blender
    with tempfile.TemporaryFile(mode='w', delete=False) as fp:
TypeError: TemporaryFile() got an unexpected keyword argument 'delete'
```
I'm sure you're working on the 2.8x version so feel free to close it as you fix the script.

**Comment by cheind** [comment]
Hi, yes thanks a lot. I'm currently quite busy, so the port to 2.8 has to pause a bit.

**Comment by cheind** [comment]
Fixed with latest version.
